In [1]:
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


In [2]:
# Import numpy as np
import numpy as np

# Create PE ratio array
pe_array = prices_array/earnings_array

# Print pe_array
print(pe_array)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


In [4]:
# Subset the first three elements
prices_subset_1 = prices_array[:3]
print(prices_subset_1)

[170.12  93.29  55.28]


In [5]:
# Subset last three elements 
prices_subset_2 = prices_array[-3:]
print(prices_subset_2)

[171.81  59.5  100.5 ]


In [3]:
# Subset every third element
prices_subset_3 = prices_array[0:7:3]
print(prices_subset_3)

[170.12 145.3  100.5 ]


In [6]:
stock_array = np.array([prices, earnings]) 
print(stock_array) 

# Print the shape of stock_array 
print(stock_array.shape) 

# Print the size of stock_array 
print(stock_array.size) 

[[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
 [  9.2    5.31   2.41   5.91  15.42   2.51   6.79]]
(2, 7)
14


In [7]:
# Create 2D array
stock_array = np.array([prices, earnings])

# Transpose stock_array
stock_array_transposed = stock_array.T
print(stock_array_transposed)

# Print the shape of stock_array
print(stock_array_transposed.shape)

# Print the size of stock_array
print(stock_array_transposed.size)

[[170.12   9.2 ]
 [ 93.29   5.31]
 [ 55.28   2.41]
 [145.3    5.91]
 [171.81  15.42]
 [ 59.5    2.51]
 [100.5    6.79]]
(7, 2)
14


In [8]:
# Subset prices from stock_array_transposed
prices = stock_array_transposed[:, 0]
print(prices)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]


In [9]:
# Subset earnings from stock_array_transposed
earnings = stock_array_transposed[:,1]
print(earnings)

[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


In [10]:
# Subset the price and earning for first company
company_1 = stock_array_transposed[0]
print(company_1)

[170.12   9.2 ]


In [11]:
# Calculate the mean 
prices_mean = np.mean(prices)
print(prices_mean)

113.6857142857143


In [12]:
# Calculate the standard deviation 
prices_std = np.std(prices)
print(prices_std)

45.51277932221513


In [13]:
import numpy as np

# Create and print company IDs
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Use array slicing to select specific company IDs
company_ids_odd = company_ids[::2]
print(company_ids_odd)

[1 2 3 4 5 6 7]
[1 3 5 7]


In [14]:
# Find the mean
price_mean = np.mean(prices)

# Create boolean array
boolean_array = prices > price_mean
print(boolean_array)

# Select prices that are greater than average
above_avg = prices[boolean_array]
print(above_avg)

[ True False False  True  True False False]
[170.12 145.3  171.81]


In [17]:
sectors = np.array()

In [19]:
sectors = np.array(["Technology", "Energy", "Financials", "Materials", "Consumer Discretionary", "Telecommunication Services", "Utilities"])
names = np.array(["Apple", "Amazon", "JPMorgan Chase", "Boeing", "Walmart", "Verizon", "AT&T"])

In [21]:
# Create boolean array
boolean_array = (sectors == 'Energy')
print(boolean_array)

# Print only health care companies
health_care = names[boolean_array]
print(health_care)

[False  True False False False False False]
['Amazon']
