In [2]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [3]:
# height_in is available as a regular list

# Import numpy
import numpy as np
height_in = [73, 74, 75, 76, 77, 78, 79, 80, 81]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*.0254

# Print np_height_m
print(np_height_m)

[73 74 75 76 77 78 79 80 81]
[1.8542 1.8796 1.905  1.9304 1.9558 1.9812 2.0066 2.032  2.0574]


In [4]:
 # height_in and weight_lb are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
weight_lb = [76, 77, 78, 79, 80, 81, 83, 84, 85]

np_weight_kg = np.array(weight_lb)*0.453592
# Calculate the BMI: bmi
bmi = np_weight_kg/(np_height_m**2)

# Print out bmi
print(bmi)


[10.02688018  9.88610546  9.74922355  9.6160754   9.48651046  9.36038618
  9.35022072  9.22778071  9.10849955]


In [5]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = np.array(bmi < 21)

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[ True  True  True  True  True  True  True  True  True]
[10.02688018  9.88610546  9.74922355  9.6160754   9.48651046  9.36038618
  9.35022072  9.22778071  9.10849955]


In [6]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [7]:
np.array([True, 1, 2]) @ np.array([3, 4, False])

7

In [8]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[0])

# Print out sub-array of np_height: index 100 up to and including index 110
print(np_height_in[1:5])

76
[74 75 76 77]


In [9]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [10]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [11]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[2,:])

# Select the entire second column of np_baseball: np_weight_lb

np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[3,0])

[210.   98.5]
188.0


In [12]:
np_baseball

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [13]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np
# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
updated = np.array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])
# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[360.  156.8]
 [430.  205.4]
 [420.  197. ]
 [376.  150.4]]
[[32400.    6146.56]
 [46225.   10547.29]
 [44100.    9702.25]
 [35344.    5655.04]]


In [14]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height
print(np.mean(np_height_in))

# Print out the median of np_height
print(np.median(np_height_in))

198.25
199.0


In [15]:
# np_baseball is available

# Import numpy
import numpy as np
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


In [16]:
# heights and positions are available as lists

# Import numpy
import numpy as np
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']


# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))


Median height of goalkeepers: 191.0
Median height of other players: 184.0


In [18]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np_city.shape

(5000, 2)